### ISSUE TITLE
send Record to DAW

### ISSUE THREAD

**Issue by oiresgleichen** [xelarep/RecordingLightHUI#1]
hello.
I Love your scetch. great work.

I hope you can help me. I want to know how I can send a Record command to my DAW?
The Syntax is 0xb0 , 0x0f , 0x0e , 0xb0 , 0x2f , 0x45 but I don't know how to send this to my computer.

thanks Kai

UPDATE.... I got it :-)       Thanks

**Comment by xelarep** [comment]
Sorry for my late reply, good to know that you've figured it out :-)
